export const AMENITY_LABELS = {
  fuel: 'АЗС',
  charging_station: 'Зарядна станція',
  pharmacy: 'Аптека',
  hospital: 'Лікарня',
  clinic: 'Клініка',
  place_of_worship: 'Храм',
  monastery: 'Монастир',
  marketplace: 'Ринок',
  bank: 'Банк',
  atm: 'Банкомат',
  restaurant: 'Ресторан',
  cafe: 'Кафе',
  fast_food: 'Фастфуд',
  pub: 'Паб',
  bar: 'Бар',
  school: 'Школа',
  kindergarten: 'Дитсадок',
  university: 'Університет',
  college: 'Коледж',
  library: 'Бібліотека',
  post_office: 'Пошта',
  townhall: 'Мерія',
  courthouse: 'Суд',
  police: 'Поліція',
  fire_station: 'Пожежна',
  bus_station: 'Автостанція',
  taxi: 'Таксі',
  theatre: 'Театр',
  car_wash: 'Автомийка',
  fountain: 'Фонтан',
};

export const AMENITY_COLORS = {
  fuel: '#ffa726',
  charging_station: '#fb8c00',
  pharmacy: '#66bb6a',
  hospital: '#ef5350',
  clinic: '#e57373',
  place_of_worship: '#ab47bc',
  monastery: '#8e24aa',
  marketplace: '#43a047',
  bank: '#42a5f5',
  atm: '#1e88e5',
  restaurant: '#ff7043',
  cafe: '#a1887f',
  fast_food: '#ff8a65',
  pub: '#bf360c',
  bar: '#d84315',
  school: '#7e57c2',
  kindergarten: '#9575cd',
  university: '#5e35b1',
  college: '#673ab7',
  library: '#7986cb',
  post_office: '#78909c',
  townhall: '#546e7a',
  courthouse: '#455a64',
  police: '#1976d2',
  fire_station: '#c62828',
  bus_station: '#fbc02d',
  taxi: '#fdd835',
  theatre: '#ce93d8',
  car_wash: '#90a4ae',
  fountain: '#26c6da',
};

export function formatPoiHint(poi) {
  const type = AMENITY_LABELS[poi.amenity] || poi.amenity;
  const name = poi.name ? `${type} ${poi.name}` : type;
  return `${name} (${poi.distanceFromLandmark}м)`;
}
